slogan: "沉淀后的符文会印在这儿，慢慢地，它们会亮起来..."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All articles."
  - title: Categories
    url: categories
    intro: "All categories."
  - title: Tags
    url: tags
    intro: "All tags."
  - title: About
    url: about
    intro: "About me."

links:
  - title: "My Github"
    url: https://github.com/OrexZ
    intro: "My Github account."
    icon: "fa fa-github"


widgets:
- search
- category
- tagcloud
- recent_posts
- links

fancybox: true
favicon: favicon.png
duoshuo_shortname:

google_analytics:
  enable: true
  siteid:
baidu_tongji:
  enable: true
  siteid:

